# Generated by Django 2.1.7 on 2019-03-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, verbose_name='IPv4 Address')),
                ('domain', models.CharField(max_length=255, verbose_name='Domain')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time of script finished')),
                ('amount', models.IntegerField(verbose_name='Amount of devices found')),
                ('execution', models.FloatField(verbose_name='NMap execution time')),
            ],
            options={
                'verbose_name': 'Data from KenCan execution',
                'verbose_name_plural': 'Data from KenCan execution',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='collect.Execution'),
        ),
    ]
